name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: 'Bump version and create changelog with commitizen'
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: 'body.md'
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Versions
        run: npm i -g json && json -I -f package.json -e "this.version=\"${{ env.REVISION }}\"" && npm i && npx react-native-version

      - name: Commit files
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            ios/CommitizenTest/Info.plist
            package.json
            android/app/build.gradle
            ios/CommitizenTest.xcodeproj/project.pbxproj
            ios/CommitizenTestTests/Info.plist
          commit-msg: bump:updated package.json, android, and IOS files to version ${{ env.REVISION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Version in Dashboard
        id: createVersionDashboardRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://1b3d-37-245-27-67.in.ngrok.io/api/v1/app-version'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"appName": "versioning_app", "version": "${{ env.REVISION }}", "platform": "REACT_NATIVE", "forceUpgrade": false, "flexibleUpgrade": true, "updateMessage": "Hi! We are excited to let you know about our latest update. This update includes bug fixes and performance improvements to make your experience better."}'
      - name: Show Create Version Response
        run: |
          echo ${{ steps.createVersionDashboardRequest.outputs.response }}
          echo ${{ steps.createVersionDashboardRequest.outputs.headers }}
